### ISSUE TITLE
`tree.py` bugs & improvements

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/gizmos#21]
* Parent terms all have the same href as the target term, so you cannot click back up them
* Terms with no label will cause the script to fail
* We should allow a default with no `term` arg that just shows the top-level under `owl:Thing`

**Comment by beckyjackson** [comment]
Also, should we add the `db` param as part of the query string? If we don't, we potentially need multiple `tree.sh` scripts for each ontology we want to browse.

**Comment by jamesaoverton** [comment]
Yeah, that sounds right.

**Comment by beckyjackson** [comment]
I'm going to wait for #18 to be merged until working on this to prevent any weird conflicts.
