### ISSUE TITLE
Sort annotations in tree view

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/gizmos#34]
When I'm browsing terms, I usually want to see annotations in a certain order. Off the top of my head:

- label
- alternative term
- definition
- definition source
- example of usage
- equivalent class
- subclass
- other logic ...
- term editor
- editor notes

Then there can be more annotations, which should probably be in alphabetical order by their label.

Logical axioms are usually at the bottom, but I'm putting them closer to the definition.

Somebody is sure to object to my preferred order, or we'll want to prioritize some annotation property for some project. So ultimately the order will have to be customizable.

**Comment by jamesaoverton** [comment]
Related to this, I just had a request for including only a subset of annotation properties.

**Comment by beckyjackson** [comment]
So I'm thinking we add an `--annotations`/`-a` option that allows you to pass a file with the list of annotations you'd like, in the order you'd like them. No additional annotations will be included unless you include `--include-all-annotations`/`-A`, what do you think? It's a little wordy but I can't think of a better phrase...

**Comment by jamesaoverton** [comment]
Sound good
