### ISSUE TITLE
Detect invalid QNames in export

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/gizmos#38]
`gizmos.extract` created a ttl file with this line in it that won't load with ROBOT:
```
IAO:0020000 IAO:0000412 obo:iao/pno.owl .
```

Another example:
```
GO:0008150 oboInOwl:inSubset obo:go#goslim_yeast .
```

`extract` should check all (?) IRIs and if they are not valid QNames, expand them to full IRIs.

**Comment by jamesaoverton** [comment]
Now I think it would be best to check all CURIEs and escape problematic characters.

**Comment by beckyjackson** [comment]
I wanted to try and be more efficient about it, but I can't get the SQLite query to work right.

Here's what I have working, but depending on how many escaped CURIEs we have, this may have to run many times:
```python
def escape_qnames(cur):
    """Find CURIEs with illegal QName characters in the local ID and escape those characters."""
    for keyword in ["stanza", "subject", "predicate", "object"]:
        cur.execute(
            f"""
            SELECT DISTINCT {keyword} FROM tmp.extract
            WHERE {keyword} NOT LIKE '<%>' AND {keyword} NOT LIKE '_:'"""
        )
        res = cur.fetchall()
        updates = {}
        for row in res:
            curie = row[keyword]
            prefix = curie.split(":")[0]
            local_id = curie.split(":")[1]
            local_id_fixed = re.sub(r"(?<!\\)([~!$&'()*+,;=/?#@%])", r"\\\1", local_id)
            if local_id != local_id_fixed:
                updates[curie] = f"{prefix}:{local_id_fixed}"

        for old, new in updates.items():
            cur.execute(f"UPDATE tmp.extract SET {keyword} = '{new}' WHERE {keyword} = '{old}'")
```

I wanted to use the CASE statement [shown here](https://stackoverflow.com/questions/41177356/sqlite-multiple-updates-in-one-query/41177390), but it deleted all the other values (non-replaced values) when I tested it out... thoughts?
