### ISSUE TITLE
Hard-coded prefixes in SQLite queries

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/gizmos#40]
We should make a list of required prefixes for the gizmos modules to work. e.g., if you don't define `rdf` or `owl` when using `extract`, no annotations will end up in the output even with this fix.

Alternatively, we search the prefixes table to get the provided prefix for these namespaces in case somebody uses a different prefix (for whatever reason...)?

**Comment by jamesaoverton** [comment]
I think this is covered by the new check command #70
