### ISSUE TITLE
Replace `curie2href` with optional `href=prefix` parameter

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/gizmos#42]
We currently link to other terms in the tree with `<a href="?id=FOO:123" ...>`, and an `include_db` option that makes it `<a href="?db=foo&id=FOO:123" ...>`. I need to be able to configure links like `<a href="./FOO:123" ...>`. In the process, I think we can drop `include_db`.

@beckyjackson and I discussed passing a format string like `f"?id={curie}"`. This would work find in Python, but not for our embedded JavaScript. So let's provide the `href` as just a prefix and append the CURIE. So I would like to be able to call `tree(db, id, href="./")` for my use case. The default would be `href="?id="`. If you want to specify a DB, you would call `tree(db, id, href="?db=FOO&id=")`.

**Comment by beckyjackson** [comment]
This means getting rid of `--include-db`, correct?

**Comment by jamesaoverton** [comment]
Good question. The command line option could stay, but we wouldn't need it as a named argument for the Python function.
