### ISSUE TITLE
Generalize to support Postgres

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/gizmos#48]
I like SQLite a lot but there are cases where Postgres is a better choice, and we should start thinking about how we can generalize Gizmos to support Postgres.

The main change will be database connections. We currently pass a `database` string to our primary functions, expecting it to be a SQLite connection string such as a filename. We should generalize this to allow a Postgres connection string. Both should return a [DB API 2.0](https://www.python.org/dev/peps/pep-0249/) connection.

From that point, I'm hoping that most of our SQL statements are standard, and don't need to be changed. If they do, I hope we can find a light-weight SQL translation layer that we can use. I'm not interested in a heavyweight ORM approach.

**Comment by beckyjackson** [comment]
What exactly should the Postgres connection string look like? A database configuration file, like `database.ini`? Otherwise I'm not sure how we would specify all the parameters. I guess we could have options like `host`, `port`, `database`, etc...

**Comment by jamesaoverton** [comment]
Good question. I'm not sure, but I see two options:

1. a dict, which the user might load from a file if they want, then we get the cursor like: `psycopg2.connect(**config)`.
2. a [connection string](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING) which is like a URL. Each SQL database has some support for this including [SQLite](https://www.sqlite.org/uri.html) but maybe not though Python? So it might be general, but it can be fiddly, e.g. require URL escaping and URL parsing.

I guess I would lean toward the connection string, but it might be a pain.

**Comment by beckyjackson** [comment]
I much prefer solution 1, and we can accept a `whatever.ini` config file from the command line like:
```
[postgresql]
host = localhost
database = customer
user = postgres
password = admindb
port = 5432
```
