### ISSUE TITLE
Tree should indicate whether a child node has children

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/gizmos#49]
Currently I have to click on a child note to see if it has children. I can't just see that it's a leaf node.

**Comment by beckyjackson** [comment]
Should this be a default, or should we add it as an option (e.g., `--show-children`)?

Also, how do we want to display it? Just as a number next to the label?
> information content entity (6)

Or do we want to do something like OLS and have a little + next to the term?

**Comment by jamesaoverton** [comment]
I was thinking of a "+" if there's children and a "-" if not. I would use CSS somehow but I'm not sure exactly how.

I think it's always useful, not just an option. It shouldn't be too expensive to compute.

No counts, at least not for now and not by default. A count is more expensive, and more often I care about the number of descendants than the number of children, which is even more expensive. It may be a good feature later. If you want it, please create a new issue.
