### ISSUE TITLE
Missing "and" for more than two conjuncts

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/gizmos#50]
Ontobee shows the logic for this MRO term correctly:

http://www.ontobee.org/ontology/MRO?iri=http://purl.obolibrary.org/obo/MRO_0000934

as 

> MHC class II protein complex and (has part some BoLA-DQA chain) and (has part some BoLA-DQB chain) and (in taxon some cattle)

Gizmos tree only has the first "and":

> ( MHC class II protein complex and has part some BoLA-DQA chain has part some BoLA-DQB chain in taxon some cattle )

The missing "and"s need to be added. It would be better with more parentheses and without the outer parentheses, just like OntoBee above.

**Comment by lmcmicu** [comment]
The way the code is written (it uses a recursive algorithm) makes it difficult to remove the outer parentheses (or at least it is difficult for me to see an obvious way to do this) except by first rendering them, and then removing them after the fact. But it's hard to remove them after the fact in a principled way and I worry that doing that would increase the risk of bugs appearing later on if we aren't aware of this logic. I hope we can live with the outer parentheses.
