### ISSUE TITLE
Create a 'check' command

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/gizmos#70]
`gizmos.check` should accept a database and make sure that the database is in the expected format. This means that it has at least two tables: `statements` and `prefix`. The columns of the tables should match what is expected from [RDFTab](https://github.com/ontodev/rdftab.rs).

**Comment by jamesaoverton** [comment]
What do you think about checking for an index on the "stanza" column? It should be possible <https://www.sqlite.org/faq.html#q7>. But maybe this is just a warning, not an error?

**Comment by beckyjackson** [comment]
I definitely don’t think that should cause a failure, but I can add it in as a warning.

**Comment by beckyjackson** [comment]
Are there any other columns we recommend to index?

**Comment by jamesaoverton** [comment]
Not right now.

An index on "stanza" is very important right now. I'm not sure about "value" and that depends on how we solve #71. This is really slow without an index on "predicate":

https://github.com/ontodev/gizmos/blob/master/gizmos/tree.py#L866

But I think the better solution is to get a list of the predicates needed for a given term and then look them up by stanza.
