### ISSUE TITLE
Consider removing psycopg2 dependency to make easier to install

### ISSUE THREAD

**Issue by cmungall** [ontodev/gizmos#82]
Maybe it's a personal problem but I have always struggled with libs that depend on ssl in os x

I am having this issue installing psycopg2:
https://stackoverflow.com/questions/26288042/error-installing-psycopg2-library-not-found-for-lssl

This is a popular SO so I am not alone.

I was able to install doing this: 

```bash
env LDFLAGS="-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib" pip --no-cache install psycopg2
```

But I am a bit more conversant with C compilation than others who may have a hard time installing gizmo

You can do a lot with gizmos with just sqlite so maybe the psycopg2 part should be optional?

For connecting to other DBMSs consider sqlalchemy and letting people install the drivers they need separately (you don't need to use the ORM layer in sqla)

**Comment by jamesaoverton** [comment]
Gizmos started with just SQLite but now we need to support Postgres. (It's true that RDFTab only supports SQLite at the moment, but it's pretty easy to import SQLite .db into Postgres, so that's what we're doing for now.)

We added psycopg2 to help with Postgres. Do you have another suggestion?

**Comment by jamesaoverton** [comment]
You seem to prefer sqlalchemy. Doesn't it have this same problem? I guess it works with multiple Postgres packages: https://docs.sqlalchemy.org/en/14/dialects/postgresql.html

**Comment by cmungall** [comment]
So I haven't actually started using sqla with postgres yet

A basic `pip install sqlalchemy` seems to have all you need for working with sqlite

It may be the case that in order to use sqla with postgres then it will be necessary to install psycopg2. I would still opt for keeping the main requirements.txt as light as possible, make sqlite the default, and then have additional optional installations for postgres users?

**Comment by jamesaoverton** [comment]
This is increasingly frustrating.

An immediate option that seems to work is installing `psycopg2-binary` from PyPI. The docs claim that this is not suited for production, though.

@beckyjackson When you have time, can you please look into using sqlalchemy for Gizmos? I don't want to use the ORM part of it. I would prefer to keep using SQL strings for the most part, with proper escaping. The key advantage is that sqlalchemy supports may SQL dialects, and they've figured out this dynamic loading thing.

Another option would be to hide the `import psycopg2` behind a conditional, remove it from `requirements.txt`, and provide instructions for the user to install `psychopg2` if needed. That's kinda what sqlalchemy does, but their system is quite complicated.
