### ISSUE TITLE
Implement case insensitive search

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/gizmos#92]
I think the current search is case sensitive, but it would be good to be able to ignore case.

**Comment by beckyjackson** [comment]
Should it always be case insensitive, or should this be a flag where, if not included, it's case sensitive?

**Comment by jamesaoverton** [comment]
I think case-insensitive should be the default. Most people will be surprised if search is case-sensitive.

I don't know whether we want to include case-sensitive as an option. Probably not.
